Sync-20200630 (#9)
* 12043: Refactor immediate load and compare.

* 12808: Port #14914 ARMARCH: no cascaded adds in addr mode for MIPS64

* 12043: Add assert isVaildSimm16 for INS_lui

* 10780: removed passed tests which need long time to run

* 13454: Fix Assertion failed 'tempReg2 != saveOperReg2'

* 12489: [MIPS64] resove double free exception

For testcase bestfit-finalize.exe, the exception infomation is

    System.InvalidOperationException: Handle is not initialized.
    at System.Runtime.InteropServices.GCHandle.ThrowIfInvalid(IntPtr handle)
    at System.Runtime.InteropServices.GCHandle.Free()
    at GCHandle_test.Program.Finalize()

* 13354: [MIPS64] PartC- Fixed error for running native-image generated by crossgen.

* 13354: [MIPS64] PartD- Implements the struct VTableCallHolder and VTableCallStub.

* 13354: [MIPS64] PartE - Implements the DynamicHelpers and some assembly function stubs.

* 13457: MIPS not use fastTailCall when JIT has more than two slot structArg

* 10780: removed passed tests in problem_list_sh.txt and problem_list.txt

* 13416: Fix about the lvStkOffs for arguments

* 12738: Implement GCCoverageInfo::SprinkleBreakpoints for MIPS64

* 13217: Use generic assert instead of inline asm break

Co-authored-by: wangrui <wangrui@loongson.cn>
Co-authored-by: Leslie Zhai <zhaixiang@loongson.cn>
Co-authored-by: wanghaomin <wanghaomin@loongson.cn>
Co-authored-by: Guoyun Sun <sunguoyun@loongson.cn>
Co-authored-by: qiaopengcheng <qiaopengcheng-hf@loongson.cn>
Co-authored-by: jiangxinshang <jiangxinshang@loongson.cn>